name: Production Deploy

on:
  push:
    branches: [ master ]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

jobs:
  quality:
    name: Quality Control
    uses: ./.github/workflows/quality_control.yml
    secrets: inherit

  production:
    name: Production Deploy
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Deploy to Production Kubernetes
        uses: gorilainvest/gorila-actions@master
        with:
          action: aws-deploy-image
          npm-token: ${{ secrets.NPM_TOKEN }}
          environment: production
          sshkey: ${{ secrets.ACTIONS_CHECKOUT_SSH }}
          ecr-access-key-id: ${{ secrets.MANAGEMENT_ECR_AWS_ACCESS_KEY_ID }}
          ecr-access-key: ${{ secrets.MANAGEMENT_ECR_AWS_SECRET_ACCESS_KEY }}
