name: Development Deploy

on:
  push:
    branches: [ develop ]

jobs:
  quality:
    name: Quality Control
    uses: ./.github/workflows/quality_control.yml
    secrets: inherit

  development:
    name: Development Deploy
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Deploy to Development Kubernetes
        uses: gorilainvest/gorila-actions@master
        with:
          action: aws-deploy-image
          npm-token: ${{ secrets.NPM_TOKEN }}
          environment: development
          sshkey: ${{ secrets.ACTIONS_CHECKOUT_SSH }}
          ecr-access-key-id: ${{ secrets.MANAGEMENT_ECR_AWS_ACCESS_KEY_ID }}
          ecr-access-key: ${{ secrets.MANAGEMENT_ECR_AWS_SECRET_ACCESS_KEY }}
