name: Build Image, Push to ECR & Deploy to EKS
on:
  push:
    branches: [ master, develop ]

jobs:
  deploy:
    name: Build Image, Push to ECR & Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: "[Development] Build Image, Push to ECR & Deploy"
      if: endsWith(github.ref, '/develop')
      uses: gorilainvest/gorila-actions@master
      with:
        action: aws-deploy-image
        npm-token: ${{ secrets.NPM_TOKEN }}
        environment: development
        sshkey: ${{ secrets.ACTIONS_CHECKOUT_SSH }}
        ecr-access-key-id: ${{ secrets.MANAGEMENT_ECR_AWS_ACCESS_KEY_ID }}
        ecr-access-key: ${{ secrets.MANAGEMENT_ECR_AWS_SECRET_ACCESS_KEY }}

    - name: "[Production] Build Image, Push to ECR & Deploy"
      if: endsWith(github.ref, '/master')
      uses: gorilainvest/gorila-actions@master
      with:
        action: aws-deploy-image
        npm-token: ${{ secrets.NPM_TOKEN }}
        environment: production
        sshkey: ${{ secrets.ACTIONS_CHECKOUT_SSH }}
        ecr-access-key-id: ${{ secrets.MANAGEMENT_ECR_AWS_ACCESS_KEY_ID }}
        ecr-access-key: ${{ secrets.MANAGEMENT_ECR_AWS_SECRET_ACCESS_KEY }}
