name: Open PR to master

on:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

jobs:
  create-pull-request:
    name: Open PR to master
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Pull Request
          uses: repo-sync/pull-request@v2
          with:
            source_branch: ${{ github.head_ref }}
            destination_branch: "master"
            github_token: ${{ secrets.GH_TOKEN }}
            pr_title: "release/${{ github.event.pull_request.title }}"
            pr_assignee: ${{ github.event.pull_request.user.login }}
            pr_reviewer: "gorilainvest/product-backend"
            