name: Lint Check, Unit Test & Build Dry Run
on:
  pull_request:
    branches: [ master, develop ]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    name: Lint Check, Unit Test & Build Dry Run
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v2

    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: "Install Dependencies"
      run: |
        npm i -g pnpm
        pnpm i --frozen-lockfile --ignore-scripts

    - name: "Execute Lint Check"
      run: pnpm lint

    - name: "Execute Unit Tests"
      run: pnpm test

    - name: "Build Application"
      run: pnpm build
